config/routes.rb
Rails.application.routes.draw do

  post 'collaborators/create'

  get 'collaborators/destroy'

  resources :wikiis

  get 'users/new'
  get 'users/create'

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root 'welcome#index'
  get 'welcome/about'

  resources :charges
  post 'charges/downgrade' => 'charges#downgrade', :as => :downgrade
  
end

app/models/wikii.rb
class Wikii < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
end

app/controllers/wikiis_controller.rb
class WikiisController < ApplicationController
  before_action :require_sign_in, except: [:index, :show, :destroy]
  def index
     @wikiis = Wikii.all
   end

  def show
  	@wikii = Wikii.find(params[:id])
  end

  def new
  	@wikii = Wikii.new
  end

  def create
     @wikii = Wikii.new
     @wikii.user_id = current_user.id
     @wikii.title = params[:wikii][:title]
     @wikii.body = params[:wikii][:body]
     @wikii.private = params[:wikii][:private]

     if @wikii.save
       flash[:notice] = "Wiki was saved."
       redirect_to @wikii, notice: "Wikii was saved successfully."
     else
       flash.now[:alert] = "There was an error saving the Wikii. Please try again."
       render :new
     end
  end

  def update
     @wikii = Wikii.find(params[:id])
     @wikii.user_id = current_user.id
     @wikii.title = params[:wikii][:title]
     @wikii.body = params[:wikii][:body]
     @wikii.private = params[:wikii][:private]

     if @wikii.save
       flash[:notice] = "Wiki was updated."
       redirect_to @wikii, notice: "Wikii was updated successfully."
     else
       flash.now[:alert] = "There was an error updating the Wikii. Please try again."
       render :new
     end
  end

  def edit
  	@wikii = Wikii.find(params[:id])
    @collaborator = Collaborator.new
  end

  def destroy
	  @wikii = Wikii.find(params[:id])

    if @wikii.destroy
		flash[:notice] = "\"#{@wikii.title}\" was deleted successfully."
		redirect_to action: :index
    else
		flash.now[:alert] = "There was an error deleting the topic."
		render :show
    end
  end
end

app/helpers/wikiis_helper.rb
module WikiisHelper
	def user_is_authorized_for_wiki?
        current_user
    end
end

app/views/wikiis/_form.html.erb
  <%= form_for wikii do |f| %>
    <% if wikii.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(wikii.errors.count, "error") %>.</h4>
        <ul>
          <% wikii.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_group_tag(wikii.errors[:title]) do %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wikii title" %>
    <% end %>

    <%= form_group_tag(wikii.errors[:body]) do %>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wikii description" %>
    <% end %>

  <% if current_user.role == "premium"%>
    <div class="checkbox form-group">
      <%= form_group_tag(wikii.errors[:private]) do %>
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private, {:checked=>false} %> Private
        <% end %>
      <% end %>
    </div>
  <% end %>

  <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>

app/views/wikiis/edit.html.erb
<h1>Edit Wiki</h1>
<div class="row">
	 <div class="col-md-4">
		   <p>Guidelines for topics:</p>
		   <ul>
		     <li>Make sure the Wiki is appropriate.</li>
		     <li>Never insult dogs.</li>
		     <li>Smile when you type.</li>
		   </ul>
	 </div>
	 <div class="col-md-8">
	   <%= render partial: 'form', locals: { wikii: @wikii } %>

	   <% if current_user.role == "premium"%>
		  <%= form_for @collaborator, :url => collaborators_create_path(:id => @wikii.id), :html => {:method => :post} do |k| %>
		      <%= form_group_tag(@collaborator.errors[:UserName]) do %>
		        <%= k.label "Add Collaborator's Name" %>
		        <%= k.text_area :UserName, rows: 1, class: 'form-control', placeholder: "Enter collaborator name" %>
		      <% end %>
		      <%= k.submit "Save", class: 'btn btn-success' %>
		  <% end %>
		<% end %>
	 </div>
</div>

app/views/wikiis/index.html.erb
<div class="col-md-4">
	<h1>All Wikis</h1>
</div>

<div class="col-md-8" style="margin-top:1.5em;">
    <%= link_to "New Wiki", new_wikii_path, class: 'btn btn-success' %>
</div>

<div class="row">
   <div class="col-md-8">
		<% @wikiis.each do |wiki| %>
			<% if current_user %>
				<% if !wiki.private || wiki.user_id == current_user.id%>
					<div class="media">
				     	<div class="media-body">
				   			<h4 class="media-heading">
				     			<%= link_to wiki.title, wikii_path(wiki) %>
				   			</h4>
				     	</div>
			   		</div>
		   		<% elsif !wiki.collaborators.empty? %>
		   			<% wiki.collaborators.each do |collaborator| %>
			   			<% if collaborator.user_id == current_user.id %>
				   			<div class="media">
						     	<div class="media-body">
						   			<h4 class="media-heading">
						     			<%= link_to wiki.title, wikii_path(wiki) %>
						   			</h4>
						     	</div>
					   		</div>
			   			<% end %>
			   		<% end %>
		   		<% end %>
			<% else %>
				<% unless wiki.private == true%>
					<div class="media">
				     	<div class="media-body">
				   			<h4 class="media-heading">
				     			<%= link_to wiki.title, wikii_path(wiki) %>
				   			</h4>
				     	</div>
			   		</div>
		   		<% end %>
			<% end %>
		<% end %>
   </div>
</div>

app/views/wikiis/new.html.erb
<h1>New Wiki</h1>
<div class="row">
 <div class="col-md-4">
   <p>Guidelines for topics:</p>
   <ul>
     <li>Make sure the Wiki is appropriate.</li>
     <li>Never insult dogs.</li>
     <li>Smile when you type.</li>
   </ul>
 </div>
 <div class="col-md-8">
   <%= render partial: 'form', locals: { wikii: @wikii } %>
 </div>
</div>

app/views/wikiis/show.html.erb
<h1><%= @wikii.title %></h1>

<% if user_is_authorized_for_wiki? %>
   <%= link_to "Edit Wiki", edit_wikii_path, class: 'btn btn-success' %>
   <%= link_to "Delete Wiki", @wikii, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
<% end %>

<div class="row">
   <div class="col-md-8">
     
     <p class="lead"><%= Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(@wikii.body).html_safe %></p>

   </div>
</div>