config/routes.rb
Rails.application.routes.draw do

  post 'collaborators/create'

  get 'collaborators/destroy'

  resources :wikiis

  get 'users/new'
  get 'users/create'

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root 'welcome#index'
  get 'welcome/about'

  resources :charges
  post 'charges/downgrade' => 'charges#downgrade', :as => :downgrade
  
end

app/views/layouts/application.html.erb
 <html>
 <head>
   <title>Wiki</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= stylesheet_link_tag    "application", media: "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
 </head>
 <body>
   <div class="container">
     <ul class="nav nav-tabs">
       <li><%= link_to "Home", root_path %></li>
       <li><%= link_to "Wiki", wikiis_path %></li>
       <li><%= link_to "About", welcome_about_path %></li>

       <div class="pull-right user-info">
        <% if current_user %>
                <div class="pull-right">
                  <%= link_to current_user.name, edit_user_registration_path %> ||
                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                </div>
        <% else %>
              <%= link_to "Sign In", new_user_session_path %> or
              <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
       </div>
     </ul>

     <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
      <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>

     <%= yield %>
   </div>
   <div style="height: 5em"></div>

 </body>
 </html>